/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/_core/profile/': RouteRecordInfo<
      '/_core/profile/',
      '/_core/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/ai-talk/': RouteRecordInfo<
      '/ai-talk/',
      '/ai-talk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth': RouteRecordInfo<
      '/auth',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | '/auth/'
      | '/auth/forgot-password'
      | '/auth/otp'
      | '/auth/sign-in'
      | '/auth/sign-in-2'
      | '/auth/sign-up'
    >,
    '/auth/': RouteRecordInfo<
      '/auth/',
      '/auth',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/forgot-password': RouteRecordInfo<
      '/auth/forgot-password',
      '/auth/forgot-password',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/otp': RouteRecordInfo<
      '/auth/otp',
      '/auth/otp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in': RouteRecordInfo<
      '/auth/sign-in',
      '/auth/sign-in',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-in-2': RouteRecordInfo<
      '/auth/sign-in-2',
      '/auth/sign-in-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/sign-up': RouteRecordInfo<
      '/auth/sign-up',
      '/auth/sign-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/analytics/': RouteRecordInfo<
      '/dashboard/analytics/',
      '/dashboard/analytics',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/workspace/': RouteRecordInfo<
      '/dashboard/workspace/',
      '/dashboard/workspace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors': RouteRecordInfo<
      '/errors',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | '/errors/'
      | '/errors/401'
      | '/errors/403'
      | '/errors/404'
      | '/errors/500'
      | '/errors/503'
    >,
    '/errors/': RouteRecordInfo<
      '/errors/',
      '/errors',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/401': RouteRecordInfo<
      '/errors/401',
      '/errors/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/403': RouteRecordInfo<
      '/errors/403',
      '/errors/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/404': RouteRecordInfo<
      '/errors/404',
      '/errors/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/500': RouteRecordInfo<
      '/errors/500',
      '/errors/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/errors/503': RouteRecordInfo<
      '/errors/503',
      '/errors/503',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/log/login/': RouteRecordInfo<
      '/log/login/',
      '/log/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/log/online/': RouteRecordInfo<
      '/log/online/',
      '/log/online',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/log/opera/': RouteRecordInfo<
      '/log/opera/',
      '/log/opera',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/online/': RouteRecordInfo<
      '/monitor/online/',
      '/monitor/online',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/redis/': RouteRecordInfo<
      '/monitor/redis/',
      '/monitor/redis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/monitor/server/': RouteRecordInfo<
      '/monitor/server/',
      '/monitor/server',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugins/config/': RouteRecordInfo<
      '/plugins/config/',
      '/plugins/config',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugins/dict/': RouteRecordInfo<
      '/plugins/dict/',
      '/plugins/dict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugins/dict/views/': RouteRecordInfo<
      '/plugins/dict/views/',
      '/plugins/dict/views',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugins/notice/': RouteRecordInfo<
      '/plugins/notice/',
      '/plugins/notice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/plugins/notice/views/': RouteRecordInfo<
      '/plugins/notice/views/',
      '/plugins/notice/views',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scheduler/manage/': RouteRecordInfo<
      '/scheduler/manage/',
      '/scheduler/manage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/scheduler/record/': RouteRecordInfo<
      '/scheduler/record/',
      '/scheduler/record',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/': RouteRecordInfo<
      '/settings/',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/account': RouteRecordInfo<
      '/settings/account',
      '/settings/account',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/appearance': RouteRecordInfo<
      '/settings/appearance',
      '/settings/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/data-permission/': RouteRecordInfo<
      '/system/data-permission/',
      '/system/data-permission',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/data-permission/rule/': RouteRecordInfo<
      '/system/data-permission/rule/',
      '/system/data-permission/rule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/data-permission/scope/': RouteRecordInfo<
      '/system/data-permission/scope/',
      '/system/data-permission/scope',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/data-rule/': RouteRecordInfo<
      '/system/data-rule/',
      '/system/data-rule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/data-scope/': RouteRecordInfo<
      '/system/data-scope/',
      '/system/data-scope',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/dept/': RouteRecordInfo<
      '/system/dept/',
      '/system/dept',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/menu/': RouteRecordInfo<
      '/system/menu/',
      '/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/role/': RouteRecordInfo<
      '/system/role/',
      '/system/role',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/system/user/': RouteRecordInfo<
      '/system/user/',
      '/system/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/_core/profile/index.vue': {
      routes:
        | '/_core/profile/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/ai-talk/index.vue': {
      routes:
        | '/ai-talk/'
      views:
        | never
    }
    'src/pages/auth.vue': {
      routes:
        | '/auth'
        | '/auth/'
        | '/auth/forgot-password'
        | '/auth/otp'
        | '/auth/sign-in'
        | '/auth/sign-in-2'
        | '/auth/sign-up'
      views:
        | 'default'
    }
    'src/pages/auth/index.vue': {
      routes:
        | '/auth/'
      views:
        | never
    }
    'src/pages/auth/forgot-password.vue': {
      routes:
        | '/auth/forgot-password'
      views:
        | never
    }
    'src/pages/auth/otp.vue': {
      routes:
        | '/auth/otp'
      views:
        | never
    }
    'src/pages/auth/sign-in.vue': {
      routes:
        | '/auth/sign-in'
      views:
        | never
    }
    'src/pages/auth/sign-in-2.vue': {
      routes:
        | '/auth/sign-in-2'
      views:
        | never
    }
    'src/pages/auth/sign-up.vue': {
      routes:
        | '/auth/sign-up'
      views:
        | never
    }
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/dashboard/analytics/index.vue': {
      routes:
        | '/dashboard/analytics/'
      views:
        | never
    }
    'src/pages/dashboard/workspace/index.vue': {
      routes:
        | '/dashboard/workspace/'
      views:
        | never
    }
    'src/pages/errors.vue': {
      routes:
        | '/errors'
        | '/errors/'
        | '/errors/401'
        | '/errors/403'
        | '/errors/404'
        | '/errors/500'
        | '/errors/503'
      views:
        | 'default'
    }
    'src/pages/errors/index.vue': {
      routes:
        | '/errors/'
      views:
        | never
    }
    'src/pages/errors/401.vue': {
      routes:
        | '/errors/401'
      views:
        | never
    }
    'src/pages/errors/403.vue': {
      routes:
        | '/errors/403'
      views:
        | never
    }
    'src/pages/errors/404.vue': {
      routes:
        | '/errors/404'
      views:
        | never
    }
    'src/pages/errors/500.vue': {
      routes:
        | '/errors/500'
      views:
        | never
    }
    'src/pages/errors/503.vue': {
      routes:
        | '/errors/503'
      views:
        | never
    }
    'src/pages/log/login/index.vue': {
      routes:
        | '/log/login/'
      views:
        | never
    }
    'src/pages/log/online/index.vue': {
      routes:
        | '/log/online/'
      views:
        | never
    }
    'src/pages/log/opera/index.vue': {
      routes:
        | '/log/opera/'
      views:
        | never
    }
    'src/pages/monitor/online/index.vue': {
      routes:
        | '/monitor/online/'
      views:
        | never
    }
    'src/pages/monitor/redis/index.vue': {
      routes:
        | '/monitor/redis/'
      views:
        | never
    }
    'src/pages/monitor/server/index.vue': {
      routes:
        | '/monitor/server/'
      views:
        | never
    }
    'src/pages/plugins/config/index.vue': {
      routes:
        | '/plugins/config/'
      views:
        | never
    }
    'src/pages/plugins/dict/index.vue': {
      routes:
        | '/plugins/dict/'
      views:
        | never
    }
    'src/pages/plugins/dict/views/index.vue': {
      routes:
        | '/plugins/dict/views/'
      views:
        | never
    }
    'src/pages/plugins/notice/index.vue': {
      routes:
        | '/plugins/notice/'
      views:
        | never
    }
    'src/pages/plugins/notice/views/index.vue': {
      routes:
        | '/plugins/notice/views/'
      views:
        | never
    }
    'src/pages/scheduler/manage/index.vue': {
      routes:
        | '/scheduler/manage/'
      views:
        | never
    }
    'src/pages/scheduler/record/index.vue': {
      routes:
        | '/scheduler/record/'
      views:
        | never
    }
    'src/pages/settings/index.vue': {
      routes:
        | '/settings/'
      views:
        | never
    }
    'src/pages/settings/account.vue': {
      routes:
        | '/settings/account'
      views:
        | never
    }
    'src/pages/settings/appearance.vue': {
      routes:
        | '/settings/appearance'
      views:
        | never
    }
    'src/pages/system/data-permission/index.vue': {
      routes:
        | '/system/data-permission/'
      views:
        | never
    }
    'src/pages/system/data-permission/rule/index.vue': {
      routes:
        | '/system/data-permission/rule/'
      views:
        | never
    }
    'src/pages/system/data-permission/scope/index.vue': {
      routes:
        | '/system/data-permission/scope/'
      views:
        | never
    }
    'src/pages/system/data-rule/index.vue': {
      routes:
        | '/system/data-rule/'
      views:
        | never
    }
    'src/pages/system/data-scope/index.vue': {
      routes:
        | '/system/data-scope/'
      views:
        | never
    }
    'src/pages/system/dept/index.vue': {
      routes:
        | '/system/dept/'
      views:
        | never
    }
    'src/pages/system/menu/index.vue': {
      routes:
        | '/system/menu/'
      views:
        | never
    }
    'src/pages/system/role/index.vue': {
      routes:
        | '/system/role/'
      views:
        | never
    }
    'src/pages/system/user/index.vue': {
      routes:
        | '/system/user/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
