from typing import Any

class _OAuth20Client:
    def __init__(self, client_id: str, client_secret: str) -> None: ...
    async def get_authorization_url(self, *, redirect_uri: str, state: str) -> str: ...
    async def get_userinfo(self, access_token: str) -> dict[str, Any]: ...

class GitHubOAuth20(_OAuth20Client): ...
class GoogleOAuth20(_OAuth20Client): ...
class LinuxDoOAuth20(_OAuth20Client): ...

class FastAPIOAuth20:
    def __init__(self, client: _OAuth20Client, *, redirect_uri: str) -> None: ...
    async def __call__(self) -> tuple[dict[str, Any], str]: ...

