from datetime import datetime
from typing import Any

class ScheduleEntry:
    app: Any
    name: str
    task: str
    args: tuple[Any, ...] | None
    kwargs: dict[str, Any] | None
    options: dict[str, Any]
    schedule: Any
    last_run_at: datetime

    def __init__(self, app: Any = ..., name: str = ..., task: str = ...) -> None: ...
    def __next__(self) -> 'ScheduleEntry': ...

class Scheduler:
    app: Any
    max_interval: float
    _heap: list[Any]

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def install_default_entries(self, data: dict[str, Any]) -> None: ...
    def schedules_equal(self, *args: Any, **kwargs: Any) -> bool: ...
    def reserve(self, entry: Any) -> Any: ...
    def setup_schedule(self) -> None: ...
    def sync(self) -> None: ...
    def tick(self, **kwargs: Any) -> float: ...
    def close(self) -> None: ...
    def update_from_dict(self, beat_dict: dict[str, dict[str, Any]]) -> None: ...
    @property
    def schedule(self) -> dict[str, Any]: ...
